services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-minha_app}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-minha_app}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  selenium:
    image: ${SELENIUM_IMAGE:-seleniarm/standalone-chromium:latest}
    shm_size: 2gb
    ports: ["4444:4444"]

  api:
    build: .
    env_file: .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-minha_app}
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]
    volumes:
      - ./data:/app/data

  app:
    build: .
    env_file: .env
    environment:
      SELENIUM_REMOTE_URL: ${SELENIUM_REMOTE_URL:-http://selenium:4444/wd/hub}
      DOWNLOAD_DIR: ${DOWNLOAD_DIR:-/app/data/dom}
      CHROME_HEADLESS: "true"
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-minha_app}
    depends_on:
      selenium:
        condition: service_started
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data

volumes:
  db_data:
